cookie:
  expiry_days: 30
  key: 28cd93b128025018e1b4bc0be1c799831079dbc811d063c5de8f632feb7fa5a4
  name: colby_auth_cookie
credentials:
  usernames:
    dagyem26:
      email: dagyem26@colby.edu
      first_name: Derek
      last_name: Agyemang Duah
      logged_in: false
      password: $2b$12$5MYTrnCM2GEJQVhylc.eKOByTdZT6AH.FJlEeDLfjQ4C4KMEnzd3q
      roles: null
    ddenat28:
      email: ddenat28@colby.edu
      first_name: Doug
      last_name: Denatale
      logged_in: false
      password: $2b$12$q1Pc1lF3iJTChdKMZsOOLOAE.iqMcYgKUxs2M4V70NOptEmM84NNW
      roles: null
    fjhoff27:
      email: fjhoff27@colby.edu
      first_name: Freddy
      last_name: Hoffmann
      logged_in: false
      password: $2b$12$a4CXV4NIsf08i7y.mUyRtO8Uxheav37cahuCqyADLJaNMh21BUnjq
      roles: null
    jgodbout:
      email: jon@polyhedral.ai
      first_name: Jon
      last_name: Godbout
      logged_in: false
      password: $2b$12$tFQ/QKtD1XWiP832WNdL..9lGu18MspEp2PRAQvKQSUVRND91MlTC
      roles: null
    jgodbout@colby.edu:
      email: jgodbout@colby.edu
      first_name: Jon
      last_name: Godbout
      logged_in: false
      password: $2b$12$34.Efet9SO8Qtx6dITui8.t3ISRKxQ0Htsy03EVPTvxlyDQHKkCGa
      password_hint: 'queens college #1'
      roles: null
    jqreed25:
      email: jqreed25@colby.edu
      first_name: Jasper
      last_name: Reed
      logged_in: false
      password: $2b$12$tAwIDSuRgIPRurxBXmZFGOM.AU5ygcyBqm7HhqByOQX05C15TROh.
      roles: null
    mcviei28:
      email: mcviei28@colby.edu
      first_name: Max
      last_name: Vieira
      logged_in: false
      password: $2b$12$/q0G8vNqDDX8TSMSBcoij.STbiBFGBvP7o/ZkAQ0U3zaPfCLNhQF2
      roles: null
    mjpeti28:
      email: mjpeti28@colby.edu
      first_name: Max
      last_name: Petite
      logged_in: false
      password: $2b$12$D2umCBtzcn6.tXw9fg2UtuFnLAEiJO0vsMOGoXYSPxZpTRFGRnkiO
      roles: null
    samoha27:
      email: samoha27@colby.edu
      first_name: Seif
      last_name: Abdelhamid
      logged_in: false
      password: $2b$12$TBLLHxUvm04AAcZryZd9QOF6v1dlSp1zXn.hwB5EYfhoFEZCsR09.
      roles: null
    shmerk26:
      email: shmerk26@colby.edu
      first_name: Samuel
      last_name: Merkatz
      logged_in: false
      password: $2b$12$HmMXF4PzAvOWjK12IC3Omek3OeIunXP4W0mkOXZS95pZHC.4W5TFC
      roles: null
    skhan26:
      email: skhan26@colby.edu
      first_name: Saad
      last_name: Khan
      logged_in: false
      password: $2b$12$hbTEUmKX5VViODQU8ugTIerFjqKUj6PIsf.QFO5of9TiTR3K4I0y6
      roles: null
    srgrov28:
      email: srgrov28@colby.edu
      first_name: Sumner
      last_name: Groves
      logged_in: false
      password: $2b$12$vtD.995gLKj2ZOTJCtYiOek6oG0bIITdf0/Ih.ShlxExn.HykbwB.
      roles: null
    txiao28:
      email: txiao28@colby.edu
      first_name: David
      last_name: Xiao
      logged_in: false
      password: $2b$12$uWw1LGSYjY1Zo3rBlMGg3OasKyXKygCLLVRhHVUbv/NceEKWK6ilm
      roles: null
    wokopa26:
      email: wokopa26@colby.edu
      first_name: William
      last_name: Kopans
      logged_in: false
      password: $2b$12$COMKIUT4qIlnXW7e6YO1aurdYzKqFDdQXTYzu5gBLLXra0WGbh1ka
      roles: null
    wytsai28:
      email: wytsai28@colby.edu
      first_name: Josh
      last_name: Tsai
      logged_in: false
      password: $2b$12$cMaZu//sZjq0ubfHNxhpiedeo7pZ2EvrCPVCuSxX.NH/yi0bRalaq
      roles: null
pre-authorized:
  emails: []
