-- ============================================================
-- AI197J: Snowflake table setup (replaces LiteralAI)
-- Run this as ACCOUNTADMIN against COLBY.AI197J
-- ============================================================

USE DATABASE COLBY;
USE SCHEMA AI197J;

-- ----- USERS -----
CREATE TABLE IF NOT EXISTS USERS (
    ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    EMAIL           VARCHAR(255) NOT NULL UNIQUE,
    FIRST_NAME      VARCHAR(100),
    LAST_NAME       VARCHAR(100),
    PASSWORD_HASH   VARCHAR(255) NOT NULL,
    SNOWFLAKE_USER  VARCHAR(255),
    SNOWFLAKE_TOKEN TEXT,
    SNOWFLAKE_TOKEN_NAME VARCHAR(255),
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ----- CHAT THREADS -----
CREATE TABLE IF NOT EXISTS CHAT_THREADS (
    ID              VARCHAR(36) PRIMARY KEY,       -- UUID
    USER_EMAIL      VARCHAR(255) NOT NULL,
    NAME            VARCHAR(500),
    MODEL_NAME      VARCHAR(255),
    MODEL_ID        VARCHAR(255),
    PROVIDER        VARCHAR(100),
    SETTINGS        VARIANT,                       -- JSON blob for all thread settings
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_THREAD_USER FOREIGN KEY (USER_EMAIL) REFERENCES USERS(EMAIL)
);

-- ----- CHAT MESSAGES -----
CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
    ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    THREAD_ID       VARCHAR(36) NOT NULL,
    ROLE            VARCHAR(20) NOT NULL,          -- 'user', 'assistant', 'system'
    CONTENT         TEXT,
    MODEL_NAME      VARCHAR(255),
    TOKEN_COUNT     NUMBER,
    METADATA        VARIANT,                       -- optional JSON metadata
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_MSG_THREAD FOREIGN KEY (THREAD_ID) REFERENCES CHAT_THREADS(ID)
);

-- ----- INDEXES -----
CREATE OR REPLACE INDEX IDX_THREADS_USER ON CHAT_THREADS(USER_EMAIL);
CREATE OR REPLACE INDEX IDX_MESSAGES_THREAD ON CHAT_MESSAGES(THREAD_ID);
CREATE OR REPLACE INDEX IDX_MESSAGES_CREATED ON CHAT_MESSAGES(THREAD_ID, CREATED_AT);

-- ----- GRANTS for the app role -----
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USERS        TO ROLE AI197J_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CHAT_THREADS TO ROLE AI197J_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE CHAT_MESSAGES TO ROLE AI197J_USER;
